spring.application.name=batchServer

spring.datasource.url=jdbc:mysql://localhost:3306/batchdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Tokyo
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.batch.jdbc.initialize-schema=always
spring.batch.job.enabled=true
spring.batch.job.name=sampleJob

logging.level.root=INFO
logging.level.org.springframework.jdbc.core=DEBUG